// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ptqgvvofhwlyxslcxvxy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB0cWd2dm9maHdseXhzbGN4dnh5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDExMjA0MTgsImV4cCI6MjA1NjY5NjQxOH0.rHxHaKf5Bh80QTM_rKRcmfJfL8Oit1oNiEJliyxbdak";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);